#!/bin/sh
SYSINFO_OUTPUT="/var/lib/asterisk/static-http/config/sysinfo_output.html"

#SYSINFO_OUTPUT="/var/lib/asterisk/static-http/config/sysinfo_output.html"

UNAME="`uname -a`"
/bin/echo "<div id=si_uname>$UNAME</div>" > $SYSINFO_OUTPUT
                
UPTIME="`uptime`"
/bin/echo "<div id=si_uptime>$UPTIME</div>" >> $SYSINFO_OUTPUT 
                  
ASTERISK="`/usr/sbin/asterisk -V`"
/bin/echo "<div id=si_astver>$ASTERISK</div>" >> $SYSINFO_OUTPUT 
                
TODAY="`date`"
/bin/echo "<div id=si_date>$TODAY</div>" >> $SYSINFO_OUTPUT 

HOSTNAME="`hostname -f`"
/bin/echo "<div id=si_hostname>$HOSTNAME</div>" >> $SYSINFO_OUTPUT 
     
IFCONFIG=`ifconfig`
/bin/echo "<div id=si_ifconfig><pre>$IFCONFIG</pre></div>" >> $SYSINFO_OUTPUT 
                         
DISKUSAGE=`df -h`
/bin/echo "<div id=si_du><pre>$DISKUSAGE</pre></div>" >> $SYSINFO_OUTPUT 
                        
MEMORYUSAGE=`free`
/bin/echo "<div id=si_free><pre>$MEMORYUSAGE</pre></div>" >> $SYSINFO_OUTPUT 


THISMONTH=`/bin/date +%b`
THISDAY=`/bin/date +%d`
THIS_DAY=`/bin/date +%_d`
/bin/grep /var/log/asterisk/messages -e "$THISMONTH\( $THISDAY\| $THIS_DAY\)" > /var/lib/asterisk/static-http/config/today_log.html

#/bin/echo "<div id=bkp_files>" >> $SYSINFO_OUTPUT 
#/bin/mkdir -p /var/lib/asterisk/gui_configbackups
#/bin/ls /var/lib/asterisk/gui_configbackups/ >> $SYSINFO_OUTPUT
#/bin/echo "</div>" >> $SYSINFO_OUTPUT 

#/bin/echo "<div id=rec_files>" >> $SYSINFO_OUTPUT 
#/bin/mkdir -p /var/lib/asterisk/sounds/record
#/bin/ls /var/lib/asterisk/sounds/record/ >> $SYSINFO_OUTPUT
#/bin/echo "</div>" >> $SYSINFO_OUTPUT 

#/bin/echo "<div id=sound_files>" >> $SYSINFO_OUTPUT 
#/bin/mkdir -p /var/lib/asterisk/sounds
#/bin/ls /var/lib/asterisk/sounds/ >> $SYSINFO_OUTPUT
#/bin/echo "</div>" >> $SYSINFO_OUTPUT 



