#!/bin/sh
SYSINFO_OUTPUT="/var/lib/asterisk/static-http/config/sysinfo_output.html"

#/bin/echo "<div id=list_files>" > $SYSINFO_OUTPUT
/bin/mkdir -p $1

if [ "$2" = "time" ]; then    
        /bin/ls $1 -r --sort=time > $SYSINFO_OUTPUT
else
	/bin/ls $1 > $SYSINFO_OUTPUT                               
fi
