#!/bin/sh

MDADM_CONF=/etc/mdadm/mdadm.conf
MAX_WAIT=7 # in seconds
PREREQ="udev"
DEVICES="sda sdb" 

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

DEVICES_FOUND=1 # assume false

find_devices() {
    DEVICES_FOUND=0 # assume all found at beginning of loop
    for drive in $DEVICES
      do
      if [ ! -e /dev/$drive ]
	  then
	  DEVICES_FOUND=1 # false
	  break
      fi
    done
}

. /scripts/functions

log_begin_msg "Inveneo RAID check"

# exit with success if no mdadm.conf
if [ ! -e $MDADM_CONF ]
then
    log_warning_msg "mdadm conf: $MDADM_CONF not found. Not running check"
    exit 0
fi

# Wait for udev to populate /dev
wait=$MAX_WAIT

while [ ! $DEVICES_FOUND -eq 0 ] && [ $wait -gt 0 ] 
  do
  sleep 1
  find_devices
  wait=$(( $wait - 1 ))
done

if [ ! $DEVICES_FOUND -eq 0 ] 
    then
    log_warning_msg "Not all devices ($DEVICES) found."
    log_warning_msg "Continuing anyway with RAID check"
fi

# run check
log_warning_msg "Running: /sbin/inv-check-superblocks.sh $MDADM_CONF"
/sbin/inv-check-superblocks.sh $MDADM_CONF
log_warning_msg "Completed check"

# run mdadm assemble 
log_warning_msg "assembling arrays"
/sbin/mdadm --assemble --scan --run

log_end_msg 
exit 0

