#!/bin/sh

MDADM_CONF=/etc/mdadm/mdadm.conf
MAX_WAIT=10 # in seconds
PREREQ="udev"
DEVICES="sda sdb" 

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac


find_devices() {
    for drive in $DEVICES
      do
      if [ ! -e $drive ]
	  then
	  return 1
      fi
    done
    return 0
}

. /scripts/functions

log_begin_msg "Inveneo RAID check"

# exit with success if no mdadm script, 'cause then we can't be running raid
if [ ! -e /scripts/local-top/mdadm ]; then
    log_warning_msg "Not /scripts/local-top/mdadm, exiting"
    exit 0
fi

if [ ! -e $MDADM_CONF ]
then
    log_warning_msg "mdadm conf: $MDADM_CONF not found. Not running check"
    exit 0
fi

# Wait for udev to populate /dev
wait=$MAX_WAIT
while [ ! find_devices ] && [ $wait -gt 0 ] 
  do
  sleep 1
  wait=$(( $wait - 1 ))
done

if [ ! find_devices ] 
    then
    log_warning_msg "Not all devices ($DEVICES) found."
    log_warning_msg "Continuing anyway with RAID check"
fi

# run check
log_warning_msg "Running: /sbin/inv_check_superblocks.sh $MDADM_CONF"
/sbin/inv_check_superblocks.sh $MDADM_CONF
log_warning_msg "Completed check"
log_end_msg 
exit 0

